<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RecordRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientRecordRepository extends EntityRepository
{
    public function queryLatest()
    {
        return $this->getEntityManager()
            ->createQuery('
                SELECT p
                FROM AppBundle:ClientRecord p                
                ORDER BY p.id DESC
            ')            
        ;
    }

    public function findLatest()
    {
        $this->queryLatest()->getResult();
    }
}
